# Generated by Django 3.0.8 on 2021-05-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210502_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
