# Generated by Django 3.0.8 on 2021-05-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210502_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
