# Generated by Django 3.0.8 on 2021-05-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
