# Generated by Django 3.0.8 on 2021-05-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='FirstName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
