# Generated by Django 3.0.8 on 2021-05-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210502_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('Overview', models.CharField(max_length=1000)),
                ('Time_upload', models.DateTimeField(auto_now_add=True)),
                ('Author', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Thumbnail', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
