# Generated by Django 3.0.8 on 2021-05-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Thumbnail',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
