# Generated by Django 3.0.8 on 2021-05-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210502_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
