# Generated by Django 3.0.8 on 2021-05-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210503_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
