# Generated by Django 3.0.8 on 2021-05-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
