# Generated by Django 3.0.8 on 2021-05-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Title', models.CharField(max_length=100, null=True)),
                ('Overview', models.CharField(max_length=1000, null=True)),
                ('Time_upload', models.DateTimeField(auto_now_add=True)),
                ('Author', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Category', models.CharField(max_length=100, null=True)),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.AlterField(
            model_name='registration',
            name='LastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
