# Generated by Django 3.0.8 on 2021-05-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210503_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
