# Generated by Django 3.0.8 on 2021-05-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('Overview', models.CharField(max_length=1000, null=True)),
                ('Time_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('Author', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Category', models.CharField(max_length=100, null=True)),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
