# Generated by Django 3.0.8 on 2021-05-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210504_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Like',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
