# Generated by Django 3.0.8 on 2021-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Like',
            field=models.CharField(default=0, max_length=400),
        ),
    ]
