# Generated by Django 3.0.8 on 2021-05-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210504_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Like',
        ),
    ]
