# Generated by Django 3.0.8 on 2021-05-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
