# Generated by Django 3.0.8 on 2021-05-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20210504_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
