# Generated by Django 3.0.8 on 2021-05-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20210505_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.registration'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
