# Generated by Django 3.0.8 on 2021-05-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20210505_1514'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('user', 'post', 'value')},
        ),
    ]
