# Generated by Django 3.0.8 on 2021-05-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_comment_subcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Subcomment',
        ),
    ]
