# Generated by Django 3.0.8 on 2021-05-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_comment_subcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ConfirmPassword',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
