# Generated by Django 3.0.8 on 2021-05-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20210506_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-Time_upload']},
        ),
    ]
