# Generated by Django 3.0.8 on 2021-05-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20210506_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
